### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by sh-cho** [gmertes/NflxMultiSubs#17]
I noticed that Netflix on Chrome/Firefox only supports 720p, which is suck :(

**Comment by gmertes** [comment]
I don't own a mac and have never developed for it. From what I can find you also need an Apple developer certificate to be able to ship the extension, which is like 100 USD per year. A mac developer is welcome to port the extension to Safari, but I won't/can't do it myself.

To solve the resolution problem you can use the [netflix-1080p](https://github.com/jangxx/netflix-1080p) extension to enable 1080p playback on Chrome, it's what I use myself (and it works together with nflxmultisubs).

**Comment by sh-cho** [comment]
I heard developer program for Safari Web extension is free, but it's not true at all. 😞

**Comment by WingCH** [comment]
I forked this project and converted it to a Safari extension, and it was successfully shelved in the mac app store, but with the following changes

1. App Icon: the original icon violated the app store Guideline 4.1, so I designed another icon myself.
2. Setting Page: Safari doesn't support `runtime.connect()`, in order to upload on the mac app store as soon as possible, so I hid the settings page, if more people need it, I will add it again in the future.

Enjoy it!

https://apps.apple.com/hk/app/multisubs-for-netflix/id1594059167?mt=12

**Comment by sh-cho** [comment]
Works like a charm! awesome

**Comment by gmertes** [comment]
@WingCH Very nice! What about keeping the name consistent with the main extension? Then we could make it an 'official' port of NflxMultiSubs.

Did you have to change anything in the JS code in `src/` to make the extension work? Would you be willing to keep the Safari version updated and in sync with my version? If you could make it so that the Safari code is contained in a separate folder without making changes to the original code in `src/` , I could pull it into my fork and you can move the Safari development here. That way the Safari version can easily be updated together with the Chrome/FF releases - but I'd still need your help cause I can't release on the mac store myself.

**Comment by WingCH** [comment]
I am worried that the user will not be able to search for the extension with "netflix", but I strongly agree to respect the original author, how about l add the word NflxMultiSubs after the current name `MultiSubs For Netflix (NflxMultiSubs)`? 

I did not change any `src/` code, i can keep the Safari version updated and in sync with your version

In fact, I just simply used [safari-web-extension-converter](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari), you can see in my [forked project](https://github.com/WingCH/NflxMultiSubs/tree/safari-web-extension)

**Comment by gmertes** [comment]
> I am worried that the user will not be able to search for the extension with "netflix", but I strongly agree to respect the original author, how about l add the word NflxMultiSubs after the current name `MultiSubs For Netflix (NflxMultiSubs)`?

Agreed, that name looks good. Thanks for your efforts, will be nice to also have a maintained Safari version. Hopefully nothing breaks in the future that will require Safari-specific code changes. 😅

Could you also update the description on the apple store page? You could use the description from the Chrome store listing, and maybe mention that it is a port of this extension for Safari. I'll add a link to the apple store listing in the readme here.

What do you think: do we pull the Safari project folder into my fork (and I give you write access to the repo), or just keep your fork separate for now? I noticed that you did have to edit `src/manifest.json` to remove the settings, so we can't merge it as is.

**Comment by WingCH** [comment]
I found that the app name and app store name can be different, so I can change the app name to `NflxMultiSubs`, and the app store name is called MultiSubs For `Netflix (NflxMultiSubs)`

I will change the name, version and description tonight and upload to the app store for approval

I feel just keep my fork,  I will keep in sync with you

**Comment by WingCH** [comment]
new version has been released

https://apps.apple.com/hk/app/nflxmultisubs/id1594059167?mt=12


I found a better way, so I changed the app name and mac app store name both to the original name `NflxMultiSubs`

![image](https://user-images.githubusercontent.com/19588517/141023144-23afe85e-f688-46da-b7ca-3c7e4b8de0a2.png)

**Comment by gmertes** [comment]
I added the mac apple store link to the readme 🥳
