### ISSUE TITLE
Functional requests under Safari

### ISSUE THREAD

**Issue by shaonianruntu** [gmertes/NflxMultiSubs#22]
Dear developers, I have some functional requests under safari.

1. Can the software icon design be updated to adapt to the new rounded rectangle style started by macOS Big Sur. The current icon size is too large, 
![2022-04-16 at 14 05 07](https://user-images.githubusercontent.com/16336682/163663868-6763c4a5-7fdc-4436-9b3f-5d2022997b7a.jpg)
and the icon displayed in Safari is not use rounded rectangle.
![2022-04-16 at 14 04 39](https://user-images.githubusercontent.com/16336682/163663864-dc171b5d-4440-4025-a6e0-d7e755b0d767.jpg)

2. Can you add functions on safari and enhance the adjustment of font size from the perspective of chrome version. At the same time, whether it can support the display of fonts in "picture in picture" mode. Currently, subtitles cannot be displayed in picture in picture mode using "PiPifier" plugin under Safari.

![2022-04-16 at 14 12 34](https://user-images.githubusercontent.com/16336682/163664067-255310a6-c770-48a1-8ed0-2cdb916cf09a.jpg)

Thanks
Nan

**Comment by gmertes** [comment]
Calling @WingCH 😺 IIRC Safari doesn't support an options page like Chrome/FF, so the options page was disabled in the Safari version. It will need modification to reintroduce it. I think we can welcome PR in the Safari [fork](https://github.com/WingCH/NflxMultiSubs/tree/safari-web-extension) if anyone wants to work on this (but it's up to WingCH).

Regarding picture in picture subtitles, I don't think this is something we should support because it relies on another extension and is too niche.

**Comment by WingCH** [comment]
Thanks for your suggestion!

1. Good idea, I will update the icon at the end of this month
2. About the picture-in-picture feature, I need more time to research it, but I've just gotten into a new job and may not have time to finish this. I'll try to add it later, and I welcome any PR from anyone!
