### ISSUE TITLE
Critical: subtitle builder is broken

### ISSUE THREAD

**Issue by gmertes** [gmertes/NflxMultiSubs#27]
Netflix changed something in the subtitle manifest, breaking the subtitle builder in the `SubtitleFactory` class. Bug is located around the `ttDownloadables` field and `targetProfile` key [here](https://github.com/gmertes/NflxMultiSubs/blob/bd1335645e7e8d55beb56e5c544981234ebc0745/src/nflxmultisubs.js#L455-L456), triggering the error catch below it. 

This is a critical breaking bug, will investigate ASAP but may not have time until the weekend. If anyone already has a fix ready, PR is welcome.

Thanks to @lampy9 for the [report](https://github.com/gmertes/NflxMultiSubs/issues/23#issuecomment-1157737659)! ( it is unrelated to the Safari issue :) )

**Comment by gmertes** [comment]
@WingCH Also pinging you here: bug has been fixed in latest commit, you could update the Safari version 🤗 You do need to check if [this commit](https://github.com/gmertes/NflxMultiSubs/commit/bd1335645e7e8d55beb56e5c544981234ebc0745) is compatible cause it introduces a new option field for the text colour, but if you use the `kDefaultSettings` object to populate the options it should be compatible.

**Comment by WingCH** [comment]
@gmertes Thanks for your notice, I just uploaded a new version to apple, this version only contains bug fixes, not updates about the settings page.
The current safari version hides the settings page, because safari is not compatible with `chrome.runtime` `postMessage`, I tried to simply use `browser.runtime `, but it seems have other problems, the settings page does not work properly, safari is not like chrome and firefox like easy to debug😵, I need extra timeto develop these features for safari, so I choose to hide the settings page, I know this is not the solution, I will study it in my free time.
