### ISSUE TITLE
Secondary subtitle has no line breaks

### ISSUE THREAD

**Issue by Abernecio** [gmertes/NflxMultiSubs#31]
Hi!
First of all, congratulations on the extension! I tested a bunch of others and this one is perfect.

However, it has a small problem that I don't if it's intentional or not. The secondary subtitle has no line breaks, making it sometimes to wrong to read.

Example:

```
- Olá. Está tudo bem?
- Sim e contigo?
- Hi! How are you? - I'm fine. How about you?
```
Could it be fixed? Or, if it's intentional, could you add a button that enables and disables line breaks?

Thank you and keep up the good work!

**Comment by gmertes** [comment]
Thanks for the feedback, but I can't take any of the credit because it was all done by the original author :D 

Good catch! Definitely not intentional. Lines breaks are supposed to be there. In fact, the code for line breaks is already there. They are just not being rendered correctly. I forgot if it worked before (I never paid attention to it 😅), or maybe it broke recently.

I have a fix ready. However, I need to do a little more testing because this may cause issues with overflow. If I create a test release for you, do you know how to load an unpacked extension to Chrome/FF and help me test it?

Before:
![image](https://user-images.githubusercontent.com/13658335/180653824-9b1408e9-ad88-418a-9efe-2204de5b8f06.png)

After:
![image](https://user-images.githubusercontent.com/13658335/180653814-9199f83e-ac6a-46fa-8a7c-e88ba8f310b7.png)

**Comment by Abernecio** [comment]
Yeah, sure.

But I'll only be available for testing after the 28th as I'm on a camping
trip and have no computer 😅

A domingo, 24/07/2022, 16:36, Gert Mertes ***@***.***>
escreveu:

**Comment by gmertes** [comment]
Thanks for the feedback, but I can't take any of the credit because it was all done by the original author :D 

Seems like this is intentional. Line breaks are explicitly replaced with white space. I think this was done to prevent issues with overflow (subs falling out of screen). But I do think this is worth trying.

I have line breaks working. However, I need to do a little more testing to make sure subs don't fall out of screen. I'll have a test release ready to test soon.

Before:
![image](https://user-images.githubusercontent.com/13658335/180656007-7bf07276-f1e6-4afa-b353-517ee576092b.png)

After:
![image](https://user-images.githubusercontent.com/13658335/180655988-1700b5a1-11fc-464f-a4db-f8f5ddf6d585.png)

**Comment by gmertes** [comment]
Created a test release [v2.3.1-alpha](https://github.com/gmertes/NflxMultiSubs/releases/tag/v2.3.1-alpha). You can download the zip and add the unpacked extension to the browser. See [INSTALL](https://github.com/gmertes/NflxMultiSubs/blob/master/INSTALL.md) for instructions (click on "Click here for manual installation instructions").

So far I haven't found any issues with overlap/overflow and it does look better imo. But would be nice if you (or anyone else reading this) could also test it on a couple of shows before I merge this change.

**Comment by Abernecio** [comment]
Ok, I've been testing v2.3.1-alpha for a couple of days (I had to remove the "-alpha" part from manifest, as it wouldn't accept it on Chrome) and so far I had no problems with overflow and the line breaks are all there

**Comment by gmertes** [comment]
> I had to remove the "-alpha" part from manifest, as it wouldn't accept it on Chrome

Oops 😳

Thanks for testing! I'll have a release with this feature out soon.
