### ISSUE TITLE
small subtitles

### ISSUE THREAD

**Issue by Seby68** [gmertes/NflxMultiSubs#41]
Good morning, this application is good, but in my opinion the possibility of varying the measurement of the subtitles should be changed, to make them both small. I can't find the zip file, to be unpacking and loaded from the PC. Being open source and with MIT license it is modifiable, especially for personal use, can it help me? Thanks I await reply.

**Comment by gmertes** [comment]
Hi @Seby68, sorry for the late reply as I was traveling. 

Assuming you found the settings page where you can adjust the subtitle size:
![image](https://user-images.githubusercontent.com/13658335/233808318-1fd74814-d551-41ac-b821-2d43aa812fb5.png)

Do you mean that these size options are not adequate for you, i.e.: the smallest size is not small enough? 

If so: yes, you could simply edit the hard coded value of the smallest size, [here](https://github.com/gmertes/NflxMultiSubs/blob/b12ff312fafa0805aa73004025ffd9ece837d2f7/src/settings.js#L48-L92). You'll need Node.js and build the extension from source yourself (`npm run build` to generate the extension files and `npm run pack` to generate a zip). 

There's also a request in #37 for more elaborate font options - it's on my to do list. Instead of fixed size options I could do a slider. Could also do a raw value input but I want to keep the settings page simple for non-tech people.

**Comment by Seby68** [comment]
Many thanks for the reply . However the program for the function it performs is excellent, I would like to reduce the size of the subtitles even more for personal needs.
