### ISSUE TITLE
File NLlxMultiSubs_v2.3.4_chrome

### ISSUE THREAD

**Issue by Seby68** [gmertes/NflxMultiSubs#42]
Hello, I wanted to ask you a request. Since you gave the zip file available , up to version 2.3.3 , why did you not continue with the others from 2.3.4 onwards ? I mean the NflxMultiSubs_v2.3.3_chrome (3) file, with which, I could easily change the text measurements. I think it 's not a problem for you to make them available on your site . I ask because , not being a programmer , I found it difficult to create the package from the 2.3.4 source code . I hope you accept my request , since , that you have an open source code and a Mit license. on the other hand I want to modify it for personal use only. Thanks, I await your reply.

**Comment by gmertes** [comment]
I stopped publishing releases with the zip because distribution of the extension is now done through the chrome/ff stores. The code in the zip is minified, so it's not supposed to be edited directly. 

But the zips are still being built on every commit (under Actions, click on the latest commit, scroll down and click on archives). The 2.3.4 zip is here: https://github.com/gmertes/NflxMultiSubs/suites/11172827027/artifacts/570636086

You should be able to find the size parameter you want to change in there (look for primaryTextScale and secondaryTextScale in settings.min.js)

**Comment by Seby68** [comment]
OK thank you . I'll try to modify it and see how it goes. If it's okay, I use it with text measures, which I prefer. Again many thanks. The Italian, which is me to understand each other, greets you and thanks you

**Comment by Seby68** [comment]
Tested, works perfectly. Ok, thanks again.
